### ISSUE TITLE
Create a credential helper library

### ISSUE THREAD

**Issue by tahpot** [verida/verida-js#112]
Take the `datastore` [credential helper](https://github.com/verida/datastore/blob/master/src/helpers/credentials.js) and upgrade it to use the new `verida-ts` library.

**Comment by cmcWebCode40** [comment]
## Questions For creating the credential helper class

i have been able  to read through the [did-jwt](https://github.com/decentralized-identity/did-jwt) and [did-jwt-vc](https://github.com/decentralized-identity/did-jwt-vc) library README.

-  Will I have to create a new credential issuer instance that was implemented in this method [createIssuer()](https://github.com/verida/datastore/blob/8b6ec0a5a58539a27abadcdeeb3e9829010f6875/src/helpers/credentials.js#L98) using our library (`account-node`) and (`client-ts`) packages?
    
-  Do we have a package that resolves the `did` document in order to verify the JWT?
 this function was implemented in this method [ _getResolver()](https://github.com/verida/datastore/blob/8b6ec0a5a58539a27abadcdeeb3e9829010f6875/src/helpers/credentials.js#L153)

- How do I create the `appContext` in order to fetch the credential URI that was implemented in this method [fetch(URI)](https://github.com/verida/datastore/blob/8b6ec0a5a58539a27abadcdeeb3e9829010f6875/src/helpers/credentials.js#L121) using our new library?

**Comment by tahpot** [comment]
>Will I have to create a new credential issuer instance that was implemented in this method createIssuer() using our library (account-node) and (client-ts) packages?

Yes.

>Do we have a package that resolves the did document in order to verify the JWT?
this function was implemented in this method _getResolver()

Yes, I created one here: https://github.com/verida/verida-js/blob/main/packages

You can see how it's used here: https://github.com/verida/verida-js/blob/main/packages/did-resolver/test/resolve.test.ts

>How do I create the appContext in order to fetch the credential URI that was implemented in this method fetch(URI) using our new library?

That method will need to be provided a connected [client instance](https://github.com/verida/verida-js/blob/main/packages/client-ts/src/client.ts).

I suggest you make the `Credential` class require as `client` instance in the constructor.

You can then call `getAccount()` to create an issuer and call `openExternalContext()` in `fetch(uri)`.

**Comment by cmcWebCode40** [comment]
> I suggest you make the Credential class require as a client instance in the constructor.

@tahpot , don't really understand this part , I was thinking the credential class will be static

**Comment by tahpot** [comment]
>@tahpot, don't really understand this part, I was thinking the credential class will be static

The credential class was going to be static, but we could change that and require it be instantiated with a `client` instance.

>Also, how do I get the did and appName in this line?

`did`: The `did` will be in the URI, not `vid`.
`appName`: This is the context name (the old library called it `appName`). I suggest that when you create the URI, you include the `context` in the URI format:

ie: `verida://<did>/<contextName>/<databaseName>/<rowId>` becomes our URI format to reference any object in the Verida network.

Happy to jump on a quick call tomorrow morning to flesh this out more.

**Comment by cmcWebCode40** [comment]
thanks,understood.

scheduling a call for tomorrow would be great
