### ISSUE TITLE
Document update conflicts showing in logs

### ISSUE THREAD

**Issue by nick-verida** [verida/verida-js#132]
I'm getting Document update conflict  a lot (30%?) of the time while use the Tutorial messaging code (which is taken directly from the Web Sandbox). 

An example is this:

```
Uncaught (in promise) 
Object { status: 409, name: "conflict", message: "Document update conflict", error: true, id: "v8644a9100f541b841d54deef10ab0d6ba2abd7a13e87fe117bebfcb725af6e85", docId: "v8644a9100f541b841d54deef10ab0d6ba2abd7a13e87fe117bebfcb725af6e85", stack: "" }​
docId: "v8644a9100f541b841d54deef10ab0d6ba2abd7a13e87fe117bebfcb725af6e85"
error: true
id: "v8644a9100f541b841d54deef10ab0d6ba2abd7a13e87fe117bebfcb725af6e85"
message: "Document update conflict"
name: "conflict"
stack: ""
status: 409
<prototype>: Object { toString: toString(), stack: "", … }
vendors-node_modules_mdx-js_react_dist_esm_js-node_modules_verida_account-web-vault_dist_inde-af8651.js line 104741 > Function:48:18
    sendMessage http://localhost:3000/vendors-node_modules_mdx-js_react_dist_esm_js-node_modules_verida_account-web-vault_dist_inde-af8651.js line 104741 > Function:48
    AsyncFunctionThrow self-hosted:699
```

**Comment by nick-verida** [comment]
Context name is `Verida: Tutorial` and changing it fixes the problem

**Comment by tahpot** [comment]
The underlying issue here was due to a Verida account created using an old version of the `client-ts` library.

Within the `client-ts` library there is a datastore that saves an index of all the databases opened within the current application context. The older `client-ts` library version used a different schema name for this datastore than the schema used in the current `client-ts` version.

This datastore is configured to always set the primary key (`id` ) of the database row to match the name of the database. However, in this instance there is already a record that exists (but with an incorrect schema) so when the library forces an attempt to save a new record it creates this `conflict` error.

The solution here is to:

- Create a new Verida account (which won't have any previous database indexes with the wrong schema)
- Change the context name (which also won't have any previous database indexes)
