### ISSUE TITLE
Database connections not being closed when messages are sent

### ISSUE THREAD

**Issue by nick-verida** [verida/verida-js#360]
From @tahpot [in Discord](https://discord.com/channels/664594912460668960/1161077815463137363/1161534159760666776):

> So... the code that sends the message creates a database instance to the remote database and then sends it, but doesn't close. It's not possible (at the moment anyway) to get that database connection and close it. So I'll need to do a protocol update to fix this

**Comment by tahpot** [comment]
Fix is in this PR: https://github.com/verida/verida-js/pull/355

**Comment by nick-verida** [comment]
Using the `develop` branch on 22-Nov-23, this doesn't seem to be fixed.

It does work correctly if I just open and close a context, but in this case it doesn't work:

```
this.veridaContext = await client.openContext("DID Message Sender", true) as Context;
const messaging = await this.veridaContext.getMessaging(); // works without this
await this.veridaContext.close();
```

**Comment by tahpot** [comment]
This should now be fixed with https://github.com/verida/verida-js/commit/69e38422d095fadfa0fbaad814ce640de9456959

However, there remains an outstanding issue where a single database connection doesn't get closed when closing the context so applications may hang at the end.

This has been logged as a separate issue (https://github.com/verida/verida-js/issues/375) so this issue can be closed.
